In [1]:
import pandas as pd
data = [10,20,30,40]
series = pd.Series(data)
series

0    10
1    20
2    30
3    40
dtype: int64

In [3]:
series = pd.Series(data,index=['a','b','c','d'])
series

a    10
b    20
c    30
d    40
dtype: int64

In [ ]:
data = {
    'Name':['Alice','Bob','charlie'],
    'Age':[25,30,35],
    'city':['New York','Los Angeles','chicago']
}
df = pd.DataFrame(data)
df

      Name  Age         city
a    Alice   25     New York
b      Bob   30  Los Angeles
c  charlie   35      chicago

In [6]:
df.info()

<class 'pandas.DataFrame'>
Index: 3 entries, a to c
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Age     3 non-null      int64
 2   city    3 non-null      str
dtypes: int64(1), str(2)
memory usage: 204.0+ bytes

In [7]:
df.describe()

        Age
count   3.0
mean   30.0
std     5.0
min    25.0
25%    27.5
50%    30.0
75%    32.5
max    35.0

In [8]:
df.dtypes

Name      str
Age     int64
city      str
dtype: object